#!/usr/bin/env node

import { execSync } from "child_process";
import fs from "fs";
import path from "path";

function runCommand(command, options = {}) {
  try {
    return execSync(command, {
      encoding: "utf8",
      stdio: options.silent ? "pipe" : "inherit",
      ...options,
    });
  } catch (error) {
    if (!options.silent) {
      console.error(`Command failed: ${command}`);
      console.error(error.message);
    }
    throw error;
  }
}

// Get the main repo root (where .git directory lives)
function getMainRoot() {
  const gitCommonDir = execSync("git rev-parse --git-common-dir", {
    encoding: "utf8",
  }).trim();
  // gitCommonDir is the .git directory — parent is the repo root
  return path.resolve(gitCommonDir, "..");
}

// Set up Claude settings.local.json symlink in a worktree
function setupClaudeSettings(mainRoot, worktreePath) {
  const sourceFile = path.join(mainRoot, ".claude", "settings.local.json");
  const targetDir = path.join(worktreePath, ".claude");
  const targetFile = path.join(targetDir, "settings.local.json");

  if (!fs.existsSync(sourceFile)) {
    console.warn(
      "  Claude settings.local.json not found in main repo — skipping symlink",
    );
    return false;
  }

  if (fs.existsSync(targetFile)) {
    // Already exists (might be a symlink or real file)
    return true;
  }

  // Ensure .claude directory exists in worktree
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  // Create relative symlink
  const relPath = path.relative(targetDir, sourceFile);
  fs.symlinkSync(relPath, targetFile);
  return true;
}

// Write .env.local with unique ports for a worktree
function setupEnvLocal(worktreePath, offset) {
  const envPath = path.join(worktreePath, ".env.local");
  if (fs.existsSync(envPath)) {
    return null; // Already configured
  }

  const vitePort = 5173 + offset;
  const inspectPort = 5858 + offset;
  const debugPort = 9229 + offset;

  const content = [
    "# Auto-generated by worktree-create — unique ports for parallel dev",
    `VITE_DEV_SERVER_PORT=${vitePort}`,
    `ELECTRON_INSPECT_PORT=${inspectPort}`,
    `REMOTE_DEBUG_PORT=${debugPort}`,
    "",
  ].join("\n");

  fs.writeFileSync(envPath, content);
  return { vitePort, inspectPort, debugPort };
}

// Count existing worktrees to determine port offset
function getWorktreeOffset(mainRoot) {
  const output = execSync("git worktree list --porcelain", {
    encoding: "utf8",
    cwd: mainRoot,
  });

  let count = 0;
  for (const line of output.split("\n")) {
    if (line.startsWith("worktree ")) {
      count++;
    }
  }
  // Main repo is count 0, first worktree is 1, etc.
  // But we want offset for the NEW worktree, which will be the current count
  // (since main is included in the count)
  return count;
}

// Parse worktree list from git
function getWorktrees(mainRoot) {
  const output = execSync("git worktree list --porcelain", {
    encoding: "utf8",
    cwd: mainRoot,
  });

  const worktrees = [];
  let current = null;

  for (const line of output.split("\n")) {
    if (line.startsWith("worktree ")) {
      if (current) worktrees.push(current);
      current = { path: line.slice("worktree ".length) };
    } else if (line.startsWith("branch ")) {
      if (current) current.branch = line.slice("branch ".length);
    }
  }
  if (current) worktrees.push(current);

  return worktrees;
}

function fixExistingWorktrees() {
  const mainRoot = getMainRoot();
  const worktrees = getWorktrees(mainRoot);

  console.log(`Found ${worktrees.length} worktree(s)`);

  let fixed = 0;
  let offset = 0;

  for (const wt of worktrees) {
    // Skip the main repo itself
    if (wt.path === mainRoot) {
      offset++;
      continue;
    }

    console.log(`\n  ${path.basename(wt.path)}:`);

    // Claude settings symlink
    const hadSettings = setupClaudeSettings(mainRoot, wt.path);
    if (hadSettings) {
      console.log("    Claude settings: linked");
    } else {
      console.log("    Claude settings: source missing (skipped)");
    }

    // .env.local ports
    const ports = setupEnvLocal(wt.path, offset);
    if (ports) {
      console.log(
        `    Ports: vite=${ports.vitePort}, inspector=${ports.inspectPort}, debug=${ports.debugPort}`,
      );
      fixed++;
    } else {
      console.log("    Ports: .env.local already exists (skipped)");
    }

    offset++;
  }

  console.log(`\nFixed ${fixed} worktree(s)`);
}

function main() {
  const taskName = process.argv[2];

  // Handle --fix mode
  if (taskName === "--fix") {
    console.log("Fixing existing worktrees...\n");
    fixExistingWorktrees();
    return;
  }

  if (!taskName) {
    console.error("Task name required");
    console.error("Usage: npm run worktree:create <task-name>");
    console.error("       node scripts/worktree-create.js --fix");
    console.error("");
    console.error("Examples:");
    console.error("  npm run worktree:create task-5.2-kit-editor");
    console.error("  npm run worktree:create fix-sample-loading");
    console.error("  node scripts/worktree-create.js --fix  # Fix existing worktrees");
    process.exit(1);
  }

  const skipInstall = process.argv.includes("--skip-install");

  // Validate task name (no spaces, reasonable characters)
  if (!/^[a-zA-Z0-9._-]+$/.test(taskName)) {
    console.error(
      "Invalid task name. Use only letters, numbers, dots, hyphens, and underscores.",
    );
    process.exit(1);
  }

  const mainRoot = getMainRoot();

  console.log(`Creating worktree for: ${taskName}`);

  // Ensure worktrees directory exists
  const worktreesDir = path.join(mainRoot, "worktrees");
  if (!fs.existsSync(worktreesDir)) {
    fs.mkdirSync(worktreesDir, { recursive: true });
  }

  const worktreePath = path.join(worktreesDir, taskName);
  const branchName = `feature/${taskName}`;

  // Check if worktree already exists
  if (fs.existsSync(worktreePath)) {
    console.error(`Worktree already exists at: ${worktreePath}`);
    process.exit(1);
  }

  // Check if branch already exists
  try {
    runCommand(`git rev-parse --verify ${branchName}`, { silent: true });
    console.error(`Branch ${branchName} already exists`);
    console.error(
      "Use: npm run worktree:remove to clean up, or choose a different task name",
    );
    process.exit(1);
  } catch {
    // Branch doesn't exist, which is what we want
  }

  console.log(`  Branch: ${branchName}`);
  console.log(`  Path:   ${worktreePath}`);

  try {
    // Create worktree with new branch
    runCommand(`git worktree add ${worktreePath} -b ${branchName}`);

    // Phase 1: Claude settings symlink
    const settingsOk = setupClaudeSettings(mainRoot, worktreePath);

    // Phase 2: Port assignment
    const offset = getWorktreeOffset(mainRoot);
    const ports = setupEnvLocal(worktreePath, offset - 1); // -1 because the new worktree is already counted

    // Phase 3: Install dependencies
    let depsInstalled = false;
    if (!skipInstall) {
      console.log("\nInstalling dependencies (this may take a minute)...");
      try {
        runCommand("npm install", { cwd: worktreePath });
        depsInstalled = true;
      } catch {
        console.error("npm install failed — you can retry manually");
      }
    }

    // Phase 4: Validation summary
    console.log("\n" + "=".repeat(50));
    console.log("Worktree ready:");
    console.log(`  Path:     worktrees/${taskName}`);
    console.log(`  Branch:   ${branchName}`);
    if (ports) {
      console.log(
        `  Ports:    vite=${ports.vitePort}, inspector=${ports.inspectPort}, debug=${ports.debugPort}`,
      );
    }
    console.log(`  Claude:   ${settingsOk ? "settings.local.json linked" : "source not found (skipped)"}`);
    console.log(`  Deps:     ${depsInstalled ? "installed" : skipInstall ? "skipped (--skip-install)" : "failed"}`);
    console.log("");
    console.log(`  cd worktrees/${taskName} && npm run dev`);
    console.log("=".repeat(50));
  } catch {
    console.error("Failed to create worktree");
    process.exit(1);
  }
}

main();
