name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies (monorepo root)
        run: npm install

      - name: Rebuild Electron native modules
        run: npm run rebuild:electron --workspace=electron

      - name: Build shared package
        run: npm run build --workspace=shared

      - name: Build app package
        run: npm run build --workspace=app

      - name: Build electron package
        run: npm run build --workspace=electron