name: End-to-End Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Show system info (debugging)
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Current directory: $(pwd)"
        shell: bash

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libxss1 \
            libasound2-dev \
            libgtk-3-0 \
            x11-utils

      - name: Configure Electron sandbox (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Configure chrome-sandbox for proper sandboxing in CI
          CHROME_SANDBOX_PATH="node_modules/electron/dist/chrome-sandbox"
          if [ -f "$CHROME_SANDBOX_PATH" ]; then
            sudo chown root "$CHROME_SANDBOX_PATH"
            sudo chmod 4755 "$CHROME_SANDBOX_PATH"
            echo "Configured chrome-sandbox with proper permissions"
            ls -la "$CHROME_SANDBOX_PATH"
          else
            echo "chrome-sandbox not found at expected path"
            find node_modules/electron -name "chrome-sandbox" -type f || echo "chrome-sandbox not found anywhere"
          fi

      - name: Setup test environment
        run: |
          mkdir -p /tmp/e2e-sdcard
          mkdir -p /tmp/e2e-test-data
          # Copy test fixtures if they exist
          if [ -d "tests/fixtures" ]; then
            cp -r tests/fixtures/* /tmp/e2e-test-data/
          fi
        shell: bash

      - name: Setup test environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir C:\temp\e2e-sdcard
          mkdir C:\temp\e2e-test-data
          if exist tests\fixtures xcopy tests\fixtures C:\temp\e2e-test-data\ /E /I /Q
        shell: cmd

      - name: Build application
        run: npm run build

      - name: Verify build output (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          echo "Checking build output..."
          ls -la dist/
          ls -la dist/electron/
          ls -la dist/electron/main/
          if [ ! -f "dist/electron/main/index.js" ]; then
            echo "ERROR: Main Electron file not found!"
            exit 1
          fi
          echo "Build verification successful"
        shell: bash

      - name: Verify build output (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "Checking build output..."
          dir dist\
          dir dist\electron\
          dir dist\electron\main\
          if (!(Test-Path "dist\electron\main\index.js")) {
            Write-Error "ERROR: Main Electron file not found!"
            exit 1
          }
          echo "Build verification successful"
        shell: pwsh

      - name: Setup virtual display (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y xvfb
          # Start Xvfb and wait for it to be ready
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 5
          # Verify display is working
          echo "Checking if display :99 is available..."
          DISPLAY=:99 xdpyinfo || echo "Display check failed, but continuing..."

      - name: Run end-to-end tests (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: npm run test:e2e
        env:
          ROMPER_SDCARD_PATH: /tmp/e2e-sdcard
          CI: true
          DISPLAY: ":99"

      - name: Run end-to-end tests (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run test:e2e
        env:
          ROMPER_SDCARD_PATH: C:\temp\e2e-sdcard
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-results-${{ matrix.os }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-screenshots-${{ matrix.os }}
          path: test-results/**/*.png
          retention-days: 7

  # Job to check if all e2e tests passed
  e2e-tests-check:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: always()
    steps:
      - name: Check e2e test results
        run: |
          if [[ "${{ needs.e2e-tests.result }}" == "success" ]]; then
            echo "All e2e tests passed!"
            exit 0
          else
            echo "Some e2e tests failed!"
            exit 1
          fi
